packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

locals {
  ami_name_sanitized = replace(regex_replace(var.ami_name_base, "[^a-zA-Z0-9-]", "-"), "--", "-")
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture                       = "x86_64"
    "block-device-mapping.volume-type" = "gp2"
    name                               = "*ubuntu-jammy-22.04-amd64-server-*"
    root-device-type                   = "ebs"
    virtualization-type                = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = var.aws_region
}

source "amazon-ebs" "ubuntu-ami" {
  ami_description = "An example of how to create a custom AMI with a simple web app on top of Ubuntu"
  ami_name        = local.ami_name_sanitized
  encrypt_boot    = false
  instance_type   = var.instance_type
  region          = var.aws_region
  source_ami      = data.amazon-ami.autogenerated_1.id
  ssh_username    = "ubuntu"
}

// source "docker" "ubuntu-docker" {
//   changes = ["ENTRYPOINT [\"\"]"]
//   commit  = true
//   image   = "gruntwork/ubuntu-test:22.04"
// }

build {
  sources = ["source.amazon-ebs.ubuntu-ami"]

  provisioner "shell" {
    inline = ["echo 'Sleeping for a few seconds to give Ubuntu time to boot up'", "sleep 30"]
    only   = ["ubuntu-ami"]
  }

  provisioner "file" {
    destination = "/tmp/packer-docker-example"
    source      = path.root
  }

  provisioner "shell" {
    inline = ["/tmp/packer-docker-example/configure-sinatra-app.sh"]
  }
}
