---
- name: Install EPEL package on {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }}
  dnf:
    name: "{{ epel_package }}"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  when: >
    ansible_distribution_major_version == '8' or
    ansible_distribution_major_version == '9'

- name: Install dnf config-manager on {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }}
  dnf:
    name: "dnf-command(config-manager)"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  when: >
    epel_enable_extras_repos and
    (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '9'
    )

- name: Install extra packages on {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }}
  dnf:
    name: "{{ epel_extra_packages }}"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  when: >
    epel_enable_extras_repos and
    (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '9'
    )